---
title: "Randomization Report (220823)"
author: "coop711"
date: "2022-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# library(xlsx)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
```

<!--# Data Reading-->

```{r, data, echo = FALSE, results = 'hide'}
load("./red_and_black_220823_data.RData")
str(class_roll)
```

# Randomization Effects

```{r, colleges, echo = FALSE}
#pander(class_roll)
#table("단과대학" = class_roll$college, "그룹" = class_roll$group)
```

## 학번 비교

### 전체 비교

```{r, echo = FALSE}
class_roll$id_2 <-
  class_roll$id %>%
  substr(1, 4) %>%
  ifelse(. <= 2016, "2016", .)
class_roll %$%
  table(.$group, .$id_2) %>%
  `colnames<-`(c("2016 이전", 2017:2022)) %>%
  pander
class_roll <- class_roll[, -9]
# pander(table("그룹" = class_roll$group, substr(class_roll$id, 1, 4)))
```

### 21학번 기준

```{r, echo = FALSE}
class_roll$id %>%
  substr(1, 4) %>%
  `>=`(2021) %>%
  ifelse("younger_21", "older_21") %>%
  factor(levels = c("younger_21", "older_21"),
         labels = c("21학번 이후", "20학번 이전")) %>%
  table(class_roll$group, .) %>%
  pander
# ID_19 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2019, 
#                        "younger_19", "older_19"), 
#                 levels = c("younger_19", "older_19"), 
#                 labels = c("19학번", "18학번 이전"))
# pander(table("그룹" = class_roll$group, "19학번 기준" = ID_19))
```


### 20학번 기준

```{r, echo = FALSE}
class_roll$id %>%
  substr(1, 4) %>%
  `>=`(2020) %>%
  ifelse("younger_20", "older_20") %>%
  factor(levels = c("younger_20", "older_20"),
         labels = c("20학번 이후", "19학번 이전")) %>%
  table(class_roll$group, .) %>%
  pander
# ID_19 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2019, 
#                        "younger_19", "older_19"), 
#                 levels = c("younger_19", "older_19"), 
#                 labels = c("19학번", "18학번 이전"))
# pander(table("그룹" = class_roll$group, "19학번 기준" = ID_19))
```

### 19학번 기준

```{r, echo = FALSE}
class_roll$id %>%
  substr(1, 4) %>%
  `>=`(2019) %>%
  ifelse("younger_19", "older_19") %>%
  factor(levels = c("younger_19", "older_19"),
         labels = c("19학번 이후", "18학번 이전")) %>%
  table(class_roll$group, .) %>%
  pander
# ID_18 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2018, 
#                        "younger_18", "older_18"), 
#                 levels = c("younger_18", "older_18"), 
#                 labels = c("18학번 이후", "17학번 이전"))
# pander(table("그룹" = class_roll$group, "18학번 기준" = ID_18))
```

### 18학번 기준

```{r, echo = FALSE}
class_roll$id %>%
  substr(1, 4) %>%
  `>=`(2018) %>%
  ifelse("younger_18", "older_18") %>%
  factor(levels = c("younger_18", "older_18"),
         labels = c("18학번 이후", "17학번 이전")) %>%
  table(class_roll$group, .) %>%
  pander
# ID_18 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2018, 
#                        "younger_18", "older_18"), 
#                 levels = c("younger_18", "older_18"), 
#                 labels = c("18학번 이후", "17학번 이전"))
# pander(table("그룹" = class_roll$group, "18학번 기준" = ID_18))
```

### 17학번 기준

```{r, id 2017, echo = FALSE}
class_roll$id %>%
  substr(1, 4) %>%
  `>=`(2017) %>%
  ifelse("younger_17", "older_17") %>%
  factor(levels = c("younger_17", "older_17"),
         labels = c("17학번 이후", "16학번 이전")) %>%
  table(class_roll$group, .) %>%
  pander
# ID_17 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2017, 
#                        "younger_17", "older_17"), 
#                 levels = c("younger_17", "older_17"), 
#                 labels = c("17학번 이후", "16학번 이전"))
# pander(table("그룹" = class_roll$group, "17학번 기준" = ID_17))
```

## 학년

```{r, year, echo = FALSE}
class_roll$year %>%
  table(class_roll$group, .) %>%
  pander
```

## 학번 뒷자리 홀짝

```{r, odd or even, echo = FALSE}
class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) %>%
  pander
# odd_even <- as.numeric(class_roll$id) %% 2
# odd_even_f <- factor(odd_even, levels = c(1, 0), labels = c("홀수", "짝수"))
# pander(table("Group"= class_roll$group, "홀짝" = odd_even_f))
# kable(table("홀짝" = odd_even_f, "Group"= class_roll$group))
```

## 많이 나오는 성씨

```{r, name, echo = FALSE}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
# f_name <- substring(class_roll$name, first = 1, last = 1)
# f_name %in% c("김","이","박")
f_name %>%
  `%in%`(c("김", "이", "박")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "기타")) %>%
  table(class_roll$group, .) %>%
  pander
# f_name_f <- factor(ifelse(f_name %in% c("김", "이", "박"), f_name, "기타"), 
#                    levels = c("김", "이", "박", "기타"))
# pander(table("Group" = class_roll$group, "Family Name" = f_name_f))
# f_name %>%
#   `%in%`(c("김", "이", "박")) %>%
#   ifelse(f_name, "기타") %>%
#   factor(levels = c("김", "이", "박", "기타")) %>%
#   table(class_roll$group, .) %>%
#   chisq.test %>%
#   pander
```

## 학적 상태

```{r, status, echo = FALSE}
class_roll$status %>%
  table(class_roll$group, .) %>%
  pander
# year_f <- factor(class_roll$year, labels = c("1학년", "2학년", "3학년", "4학년"))
# pander(table("Group" = class_roll$group, "학년" = year_f))
```

## e-mail 서비스

```{r, e_mail, echo = FALSE}
class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  `==`("naver.com") %>%
  ifelse("네이버", "기타서비스") %>%
  factor(levels = c("네이버", "기타서비스")) %>%
  table(class_roll$group, .) %>%
  pander
# email_list <- strsplit(class_roll$email, "@", fixed = TRUE)
# mail_com <- sapply(email_list, "[", 2)
# mail_com_f <- factor(ifelse(mail_com == "naver.com", "네이버", "기타서비스"), 
#                      levels = c("네이버", "기타서비스"))
# pander(table("그룹" = class_roll$group, "e-mail" = mail_com_f))
class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  `==`("naver.com") %>%
  ifelse("네이버", "기타서비스") %>%
  factor(levels = c("네이버", "기타서비스")) %>%
  table(class_roll$group, .) %>%
  chisq.test %>%
  pander
```

## 학과

```{r, departments, echo = FALSE}
class_roll %$%
  table(.$group, .$dept) %>%
  pander
# pander(table("그룹" = class_roll$group, "학과" = class_roll$dept))
```

## 전화번호 끝 네 자리의 분포

### 분포표

```{r, echo = FALSE}
cell_numbers <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric)
# cell_numbers <- sapply(substr(class_roll$cell_no, start = 10, stop = 13), 
#                       as.numeric)
# cut_label <- c("1000~1999", "2000~2999", "3000~3999", "4000~4999", "5000~5999", "6000~6999",
#                "7000~7999", "8000~8999", "9000~9999")
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
cell_numbers %>%
  cut(labels = cut_label, breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) %>%
#  t %>%
  kable
# kable(t(table(cut(cell_numbers, 
#                   labels = cut_label, 
#                   breaks = seq(0, 10000, by = 1000)))))
cell_numbers %>%
  cut(labels = cut_label, breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) %>%
#  t %>%
  chisq.test %>%
  pander
```

### 히스토그램

```{r, echo = FALSE}
cell_numbers %>% 
  hist(main = "Cell Phone Number Last 4 Digits")
# hist(cell_numbers)
```

<!--

```{r, save, echo=FALSE, message=FALSE, results='hide'}
save.image("../R/red_and_black_220823_data.RData")
```

-->