---
title: "Red and Black 220305"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(readxl)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
load("./red_and_black_220225_data.RData")
class_roll0225 <- class_roll[, -8]
nrow(class_roll0225)
# class_roll <- read.xlsx("../data/class_roll220305.xlsx", 
#                         sheetIndex = 1, 
#                         startRow = 1, 
#                         endRow = 493, 
#                         header = TRUE,
#                         colIndex = c(2:7), 
#                         colClasses = rep("character", 6), 
#                         encoding = "UTF-8",
#                         stringsAsFactors = FALSE)
class_roll <- read_excel("../data/class_roll220305.xlsx",
                         range = "B1:G915",
                         col_names = TRUE,
                         col_types = "text")
nrow(class_roll)
nrow(class_roll0225)
names(class_roll) <- c("dept", "id", "name", "status", "email", "cell_no")
# class_roll[c(130, 284), ]
# class_roll <- class_roll[-c(130, 284), ]
class_roll$status <- ifelse(is.na(class_roll$status), "휴학", class_roll$status)
str(class_roll)
class_roll0225$mark <- "0225"
class_roll$mark2 <- "0305"
class_roll.merged <- merge(class_roll, class_roll0225, 
                           by = "id", all = TRUE)
```

<!--
### 8월 29일자 출석부와 9월 4일자 출석부 통합 결과

```{r, echo = FALSE, results = "hide"}
nrow(class_roll.merged)
pander(class_roll.merged[, c("group", "mark1", "mark2")])
```
-->

### 2월 28일자 출석부에만 나오는 사람들의 분포

```{r, echo = FALSE}
class_roll.out <- class_roll.merged[is.na(class_roll.merged$mark2), ]
pander(class_roll.out[, c("group", "mark", "mark2")])
pander(table(class_roll.out$group))
# pander(class_roll.merged[is.na(class_roll.merged$mark2), 
#                          c("group", "mark1", "mark2")])
# pander(table(class_roll.merged[is.na(class_roll.merged$mark2), ]$group))
```

```{r, echo = FALSE, results = "markup"}
id0225 <- class_roll0225$id
id0305 <- class_roll$id
stay0305 <- intersect(id0225, id0305)
length(stay0305)
new_id <- setdiff(id0305, id0225)
class_roll.stay <- subset(class_roll0225, id %in% stay0305)
class_roll.new <- subset(class_roll, id %in% new_id)
```

### 2월28일 출석부에도 나오는 사람들의 데이터 구조

```{r, echo = FALSE}
str(class_roll.stay)
```

### 수강신청 변경으로 나간 사람들의 데이터 구조

```{r, echo = FALSE}
str(class_roll.out)
```

### 수강 신청 변경으로 새로 들어온 사람들의 데이터 구조

```{r, echo = FALSE}
str(class_roll.new)
```

### 남아 있던 사람들 + 새로 들어온 사람들

```{r, echo = FALSE}
str(class_roll)
```

### 새로 들어온 사람에게만 랜덤화 적용

```{r, sub randomization, echo = FALSE, eval = TRUE}
set.seed(365787)
N <- nrow(class_roll.new) 
N_red <- table(class_roll.out$group)[1]
id_red <- sample(1:N, size = 82)
# id_red <- sample(1:N, size = 7)
id_black <- setdiff(1:N, id_red)
class_roll.new$group <- ifelse(1:N %in% id_red, "Red", "Black")
class_roll.new$group <- factor(class_roll.new$group, 
                           levels = c("Red", "Black"))
# class_roll.new$group <- factor(class_roll.new$group, 
#                            labels = c("Red", "Black"))
class_roll.new <- class_roll.new[, c(1:6, 8, 7)]
names(class_roll.stay)[8] <- "mark"
names(class_roll.new)[8] <- "mark"
# red.id <- which(class_roll.new$group == "Red")
# black.id <- which(class_roll.new$group == "Black")
class_roll <- rbind(class_roll.stay, class_roll.new)
```

### 학번

```{r, id}
class_roll %$%
  table(.$group, .$id %>% substr(1, 4)) %>%
  pander
class_roll %$%
  substr(.$id, 1, 4) %>%
  `>=`(2019) %>%
  ifelse("younger_19", "older_19") %>%
  factor(levels = c("younger_19", "older_19")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 학번 홀짝

```{r, odd or even}
class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 학적 상태

```{r, status}
class_roll$status %>%
  table(class_roll$group, .) %>%
  pander
```

### e-mail 서비스업체

```{r, e_mail}
class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  table(class_roll$group, .) %>%
  pander
```

### 전화번호의 분포

```{r}
cell_numbers <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric)
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) %>%
  kable
cell_numbers %>%
  hist
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) %>%
  chisq.test
```

### 성씨 분포

```{r, name}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
f_name %>%
  table(class_roll$group, .) %>%
  pander
```

### 많이 나오는 성씨

```{r, frequent names}
f_name %>%
  `%in%`(c("김", "이", "박")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "기타")) %>%
  table(class_roll$group, .) %>%
  pander
```

### 학과

```{r, departments}
# pander(class_roll)
class_roll %$%
  table(.$group, .$dept) %>%
  pander
```

<!--
### 전체 출석부

```{r}
class_roll %$%
  order(.$name) %>%
  class_roll[., c("id", "name", "group")] %>%
  pander(caption = "가나다순", row.names = FALSE)
```

<P style="page-break-before:always">

```{r, echo = FALSE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Red", select = c("id", "name")) %>%
  pander(caption = "Red")
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Black", select = c("id", "name")) %>%
  pander(caption = "Black")
```

<P style="page-break-before:always">

```{r, save}
class_roll %>%
  `[`(.$id %>% order, c("id", "group")) %>%
  saveRDS(file = "./class_id_group220305.RDS")
save.image("./red_and_black_220305_data.RData")
```
-->