---
title: "Red and Black 210829"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# library(xlsx)
library(readxl)
library(pander)
library(knitr)
library(magrittr)
panderOptions('table.split.table', Inf)
```

## Data

```{r, data}
class_roll <- read_excel("../data/class_roll210829.xlsx", 
                        range = "B1:G617")
str(class_roll)
# class_roll <- read_excel("../data/class_roll210829.xlsx", 1, 
#                         startRow = 1, 
#                         endRow = 487, 
#                         colIndex = c(2:7), 
#                         colClasses = rep("character", 6), 
#                        stringsAsFactors = FALSE)
names(class_roll) <- c("dept", "id", "name", "status", "email", "cell_no")
class_roll$status <- ifelse(is.na(class_roll$status), "휴학", class_roll$status)
str(class_roll)
```

## Randomization

```{r, randomization}
set.seed(9692527)
N <- nrow(class_roll) 
class_roll$group <- 
  sample(1:N) %%
  2 %>%
  factor(levels = c(0, 1), labels = c("Red", "Black"))
```

### 학번

```{r, id}
class_roll$id_2 <-
  class_roll$id %>%
  ifelse(. <= 2015, "2015", .)
class_roll %$%
  table(.$group, .$id_2 %>% substr(1, 4)) %>%
  pander
# pander(table("그룹" = class_roll$group, substr(class_roll$id, 1, 4)))
class_roll %$%
  substr(.$id, 1, 4) %>%
  `>=`(2020) %>%
  ifelse("younger_20", "older_20") %>%
  factor(levels = c("younger_20", "older_20")) %>%
  table(class_roll$group, .) %>%
  pander
# ID_19 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2019, "younger_19", "older_19"), 
#                 levels = c("younger_19", "older_19"))
# pander(table("그룹" = class_roll$group, "19학번 기준" = ID_19))
# ID_18 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2018, "younger_18", "older_18"), 
#                 levels = c("younger_18", "older_18"))
# pander(table("그룹" = class_roll$group, "18학번 기준" = ID_18))
# ID_17 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2017, "younger_17", "older_17"), 
#                 levels = c("younger_17", "older_17"))
# pander(table("그룹" = class_roll$group, "17학번 기준" = ID_17))
# ID_16 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2016, "younger_16", "older_16"), 
#                 levels = c("younger_16", "older_16"))
# pander(table("그룹" = class_roll$group, "16학번 기준" = ID_16))
# ID_15 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2015, "younger_15", "older_15"), 
#                 levels = c("younger_15", "older_15"))
# pander(table("그룹" = class_roll$group, "15학번 기준" = ID_15))
# ID_14 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2014, "younger_14", "older_14"), 
#                 levels = c("younger_14", "older_14"))
# pander(table("그룹" = class_roll$group, "14학번 기준" = ID_14))
```

### 학번 홀짝

```{r, odd or even}
class_roll$id %>%
  as.numeric %>%
  `%%`(2) %>%
  factor(levels = c(1, 0), labels = c("홀", "짝")) %>%
  table(class_roll$group, .) %>%
  pander
# odd_even <- as.numeric(class_roll$id) %% 2
# odd_even <- factor(odd_even, levels = c(1, 0), labels = c("홀", "짝"))
# pander(table("Group"= class_roll$group, "odd_even" = odd_even))
```

### 학적 상태

```{r, status}
class_roll$status %>%
  table(class_roll$group, .) %>%
  pander
```

### e-mail 서비스업체

```{r, e_mail}
class_roll$email %>%
  strsplit("@", fixed = TRUE) %>%
  sapply("[", 2) %>%
  table(class_roll$group, .) %>%
  pander
# email_list <- strsplit(class_roll$email, "@", fixed = TRUE)
# mail_com <- sapply(email_list, "[", 2)
# pander(table("그룹" = class_roll$group, "e-mail" = mail_com))
```

### 전화번호의 분포

```{r, cell_no}
par(family = "KoPubWorldDotum Bold")
# cell_numbers <- sapply(substr(class_roll$cell_no, 
#                               start = 10, stop = 13),
#                        as.numeric)
cell_numbers <- class_roll$cell_no %>%
  substr(start = 8, stop = 11) %>%
  sapply(as.numeric)
cut_label <- paste(paste0(0:9, "000"), paste0(0:9, "999"), 
                   sep = "~")
# kable(t(table(cut(cell_numbers, 
#                   labels = cut_label, 
#                   breaks = seq(0, 10000, by = 1000)))))
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table(class_roll$group, .) %>%
#   t %>%
  kable
cell_numbers %>%
  hist(main = "전화번호 끝 네 자리의 분포")
# hist(cell_numbers)
cell_numbers %>%
  cut(labels = cut_label, 
      breaks = seq(0, 10000, by = 1000)) %>%
  table %>%
  chisq.test
# chisq.test(table(cut(cell_numbers, 
#                   labels = cut_label, 
#                   breaks = seq(0, 10000, by = 1000))))
```

### 성씨 분포

```{r, name}
f_name <- class_roll$name %>%
  substring(first = 1, last = 1) 
f_name %>%
  table(class_roll$group, .) %>%
  pander
# f_name <- substring(class_roll$name, first = 1, last = 1)
# pander(table("Group" = class_roll$group, "Family Name" = f_name))
```

### 많이 나오는 성씨

```{r, frequent names}
f_name %>%
  `%in%`(c("김", "이", "박")) %>%
  ifelse(f_name, "기타") %>%
  factor(levels = c("김", "이", "박", "기타")) %>%
  table(class_roll$group, .) %>%
  pander
# f_name_f <- factor(ifelse(f_name %in% c("김", "이", "박"), f_name, "기타"), 
#                    levels = c("김", "이", "박", "기타"))
# pander(table("Group" = class_roll$group, "Family Name" = f_name_f))
```

### 학과

```{r, departments}
# pander(class_roll)
class_roll %$%
  table(.$group, .$dept) %>%
  pander
# pander(table("그룹" = class_roll$group, "학과" = class_roll$dept))
```

### 전체 출석부

```{r, colleges}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  pander(row.names = FALSE)
# pander(class_roll)
# table("단과대학" = class_roll$college, "그룹" = class_roll$group)
```

<P style="page-break-before:always">

```{r, list, echo = FALSE}
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Red", select = c("id", "name")) %>%
  pander(caption = "Red")
# gr_id_o <- order(class_roll$group, class_roll$name)
# id_by_gr <- class_roll[gr_id_o, c("group", "id", "name")]
# red_names <- id_by_gr[id_by_gr$group == "Red", c("id", "name")]
# names(red_names) <- c("학번", "이름")
# pander(red_names)
class_roll %$%
  order(.$group, .$name) %>%
  class_roll[., c("group", "id", "name")] %>%
  subset(.$group == "Black", select = c("id", "name")) %>%
  pander(caption = "Black")
# black_names <- id_by_gr[id_by_gr$group == "Black", c("id", "name")]
# names(black_names) <- c("학번", "이름")
```

<!--
```{r, save}
save.image("./red_and_black_210829_data.RData")
```
-->